const express = require("express")
const route = express.Router()
const {signup} = require("../controllers/signup")
const {login} = require("../controllers/login")
const {forgot_password} = require("../controllers/forgot_password")
const {reset_password} = require("../controllers/reset_password")
const {isLoggedin,isAdmin} = require("../middlewares/auths")
const {addItem} = require("../controllers/addItem")
const {deleteItem} = require("../controllers/deleteItem")
const {updateItem} = require("../controllers/updateItem")
const {getItems} = require("../controllers/getItems")
const customer = require("../controllers/customer")
const order = require("../controllers/order")
const admindashboard = require("../controllers/admindashboard")
const user = require("../controllers/user")
route.get("/",(req,res)=>{
    res.send("Backend Working fine")
})

route.post("/signup",signup)
route.post("/login",login)
route.post("/forgot_password",forgot_password)
route.post("/reset_password",reset_password)
route.post("/additem", addItem)
route.delete("/deleteitem/:id", deleteItem)
route.post("/updateItem/:id", updateItem)
route.post("/order/create", order.create)
route.get("/order/get", order.get)
route.put("/order/update/:id", order.update)
route.get("/getusers", user.get)
route.put("/updateuser/:id", user.update)
route.get("/getItems", getItems)
route.get("/getdashboard",admindashboard.getdashboard)
route.get("/home",customer.home)
route.get("/admin",isLoggedin,isAdmin,(req,res)=>{
    res.send("Authorised user")
})
module.exports = route