const express = require("express")
const route = express.Router()
const {signup} = require("../controllers/signup")
const {login} = require("../controllers/login")
const {forgot_password} = require("../controllers/forgot_password")
const {reset_password} = require("../controllers/reset_password")
const {isLoggedin,isAdmin} = require("../middlewares/auths")
const {addItem} = require("../controllers/addItem")
const {deleteItem} = require("../controllers/deleteItem")
const {updateItem} = require("../controllers/updateItem")
const {getItems} = require("../controllers/getItems")
const customer = require("../controllers/customer")
const order = require("../controllers/order")
const admindashboard = require("../controllers/admindashboard")
const user = require("../controllers/user")
route.get("/",(req,res)=>{
    res.send("Backend Working fine")
})

route.post("/signup",signup)
route.post("/login",login)
route.post("/forgot_password",forgot_password)
route.post("/reset_password",reset_password)
route.post("/additem",isLoggedin,isAdmin, addItem)
route.delete("/deleteitem/:id",isLoggedin,isAdmin, deleteItem)
route.post("/updateItem/:id",isLoggedin,isAdmin, updateItem)
route.post("/order/create",isLoggedin, order.create)
route.get("/order/get",isLoggedin,isAdmin, order.get)
route.post("/getdetails",isLoggedin, order.getDetails)
route.put("/order/update/:id",isLoggedin,isAdmin, order.update)
route.get("/userorder",isLoggedin, order.userorder)
route.get("/getusers",isLoggedin, user.get)
route.put("/updateuser/:id",isLoggedin, user.update)
route.get("/getItems",isLoggedin,isAdmin, getItems)
route.get("/getdashboard",isLoggedin,isAdmin,admindashboard.getdashboard)
route.get("/home",isLoggedin,customer.home)
route.get("/products",isLoggedin,customer.products)
route.get("/services",isLoggedin,customer.services)
route.get("/admin",isLoggedin,isAdmin,(req,res)=>{
    res.send("Authorised user")
})
module.exports = route